#1: Utilizar todos los argumentos pasados
tomasaccini/valgreen pull request #2
Opened 2019-11-06 19:22 UTC by mbuchwald

Creo que se está haciendo un overkill usando parse args siendo que solo se va a recibir un parámetro (que además no debería tener nombre). Particularmente esto genera que si paso más de un parámetro, pinche valgreen. Seguramente se puede configurar para tener "resto opcionales" pero dudo que valga la pena.

(fixes #1)

2019-11-28 03:49 UTC, dato requested changes

2019-11-28 03:49 UTC, dato commented on valgreen
> +    valgrind = subprocess.Popen(["valgrind", *flags].extend(exec),
`extend()` devuelve None por lo que la lista se pierde. Corresponde `["valgrind", *flags] + exec`, o quizás `["valgrind", *flags, *exec]`.

2020-01-11 22:46 UTC, FdelMazo commented on valgreen
>  def call_valgrind(exec, flags=VFLAGS):
```suggestion
def call_valgrind(executable, flags=VFLAGS):
```

2020-01-11 22:47 UTC, FdelMazo commented on valgreen
> +    valgrind = subprocess.Popen(["valgrind", *flags].extend(exec),
```suggestion
    valgrind = subprocess.Popen(["valgrind", *flags, *executable],
```

2020-01-11 22:52 UTC, FdelMazo commented on valgreen
> +    valgrind = subprocess.Popen(["valgrind", *flags].extend(exec),
```suggestion
    valgrind = subprocess.Popen(["valgrind", *flags, *exec],
```

2020-01-14 17:11 UTC, merged